INSERT INTO states(id, ulke_id, name, teslimat, shipping_price) VALUES ('1',187,'Al Daayen',1,10);
INSERT INTO states(id, ulke_id, name, teslimat, shipping_price) VALUES ('2',187,'Al Khor',1,10);
INSERT INTO states(id, ulke_id, name, teslimat, shipping_price) VALUES ('3',187,'Al Rayyan',1,10);
INSERT INTO states(id, ulke_id, name, teslimat, shipping_price) VALUES ('4',187,'Al Shamal',1,10);
INSERT INTO states(id, ulke_id, name, teslimat, shipping_price) VALUES ('5',187,'Al Wakrah',1,10);
INSERT INTO states(id, ulke_id, name, teslimat, shipping_price) VALUES ('6',187,'Doha',1,10);
INSERT INTO states(id, ulke_id, name, teslimat, shipping_price) VALUES ('7',187,'Umm Salal',1,10);


INSERT INTO cities(id,state_id,name,teslimat) VALUES(1,4,'Abu Dhalouf',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(2,3,'Abu Hamour',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(3,3,'Abu Samra',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(4,3,'Ain Khaled',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(5,4,'Ain Sinan',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(6,3,'Al Aziziya',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(7,3,'Baaya',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(8,3,'Bani Hajer',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(9,6,'Barahat Al Jufairi',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(10,7,'Bu Fasseela',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(11,3,'Bu Samra',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(12,3,'Bu Sidra',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(13,6,'Al Bidda',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(14,6,'Dahl Al Hammam',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(15,6,'Doha International Airport',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(16,6,'Doha Port',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(17,6,'Duhail',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(18,3,'Dukhan',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(19,1,'Al Daayen',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(20,6,'Al Dafna',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(21,6,'Ad Dawhah al Jadidah',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(22,1,'Al Ebb',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(23,6,'Al Egla',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(24,4,'Fuwayrit',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(25,6,'Fereej Abdel Aziz',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(26,6,'Fereej Bin Dirham',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(27,6,'Fereej Bin Mahmoud',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(28,6,'Fereej Bin Omran',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(29,6,'Fereej Kulaib',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(30,6,'Fereej Mohammed Bin Jassim',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(31,3,'Fereej Al Amir',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(32,3,'Fereej Al Asiri',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(33,6,'Fereej Al Asmakh',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(34,3,'Fereej Al Murra',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(35,3,'Fereej Al Manaseer',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(36,6,'Fereej Al Nasr',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(37,3,'Fereej Al Soudan',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(38,3,'Fereej Al Zaeem',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(39,3,'Gharafat Al Rayyan',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(40,3,'Al Gharafa',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(41,2,'Al Ghuwariyah',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(42,6,'Hamad Medical City',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(43,6,'Hazm Al Markhiya',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(44,6,'Al Hilal',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(45,6,'Industrial Area',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(46,3,'Izghawa (Al Rayyan)',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(47,7,'Izghawa (Umm Salal)',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(48,6,'Jabal Thuaileb',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(49,6,'Jelaiah',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(50,1,'Jeryan Jenaihat',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(51,6,'Jeryan Nejaima',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(52,6,'Al Jasrah',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(53,2,'Al Jeryan',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(54,5,'Khawr al Udayd',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(55,5,'Al Karaana',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(56,5,'Al Kharrara',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(57,7,'Al Kharaitiyat',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(58,6,'Al Kharayej',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(59,1,'Al Kheesa',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(60,2,'Al Khor',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(61,6,'Al Khulaifat',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(62,1,'Leabaib',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(63,3,'Lebday',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(64,6,'Lejbailat',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(65,6,'Lekhwair',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(66,6,'Leqtaifiya (West Bay Lagoon)',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(67,3,'Lijmiliya',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(68,3,'Luaib',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(69,1,'Lusail',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(70,3,'Al Luqta',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(71,4,'Madinat ash Shamal',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(72,4,'Madinat Al Kaaban',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(73,6,'Madinat Khalifa North',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(74,6,'Madinat Khalifa South',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(75,3,'Mebaireek',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(76,3,'Mehairja',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(77,5,'Mesaieed',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(78,5,'Mesaieed Industrial Area',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(79,3,'Mesaimeer',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(80,6,'Al Messila',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(81,3,'Muaither',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(82,3,'Muraikh',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(83,6,'Mushayrib',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(84,3,'Al Mamoura',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(85,6,'Al Mansoura',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(86,6,'Al Markhiyah',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(87,5,'Al Mashaf',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(88,1,'Al Masrouhiya',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(89,6,'Al Mearad',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(90,6,'Al Mirqab',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(91,6,'Najma',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(92,6,'New Al Hitmi',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(93,6,'New Al Mirqab',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(94,3,'New Al Rayyan',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(95,6,'New Salata',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(96,3,'New Fereej Al Ghanim',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(97,3,'New Fereej Al Khulaifat',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(98,6,'Nu`ayjah',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(99,6,'Al Najada',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(100,3,'Al Nasraniya',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(101,6,'Old Airport',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(102,6,'Old Al Ghanim',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(103,6,'Old Al Hitmi',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(104,3,'Old Al Rayyan',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(105,6,'Onaiza',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(106,6,'The Pearl',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(108,6,'Al Qassar',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(109,6,'Ras Abu Aboud',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(110,2,'Ras Lafan',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(111,1,'Rawdat Al Hamama',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(112,6,'Rawdat Al Khail',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(113,3,'Rawdat Egdaim',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(114,3,'Rawdat Rashed',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(115,6,'Rumaila',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(116,4,'Ar Ru\'ays',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(117,6,'Al Rufaa',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(118,3,'Sawda Natheel',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(119,5,'Shagra',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(120,2,'Simaisma',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(121,6,'Al Sadd',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(122,6,'As Salatah',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(123,3,'Al Sailiya',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(124,1,'Al Sakhama',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(125,3,'Al Shagub',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(126,3,'Al-Shahaniya',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(127,6,'Al Souq',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(128,6,'Al Seej',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(129,6,'Al Tarfa',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(130,2,'Al Thakhira',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(131,3,'Al Themaid',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(132,6,'Al Thumama (Doha)',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(133,5,'Al Thumama (Al Wakrah)',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(134,3,'Umm Bab',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(135,2,'Umm Birka',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(136,6,'Umm Ghuwailina',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(137,6,'Umm Lekhba',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(138,1,'Umm Qarn',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(139,7,'Umm Salal Ali',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(140,7,'Umm Salal Mohammed',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(141,3,'Al Utouriya',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(142,6,'Wadi Al Banat',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(143,6,'Wadi Al Sail',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(144,1,'Wadi Al Wasaah',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(145,1,'Wadi Lusail',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(146,3,'Al Waab',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(147,3,'Al Wajba',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(148,5,'Al Wakrah',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(149,5,'Al Wukair',1);
INSERT INTO cities(id,state_id,name,teslimat) VALUES(150,4,'Al Zubarah',1);
